const assert=require("node:assert/strict");
const vm=require("node:vm");
const fs=require("node:fs");
const scoring=require("../src/scoring");
const history=require("../src/history");
const base={protocol:"https:",headers:{"strict-transport-security":"max-age=31536000","content-security-policy":"default-src 'self'; script-src https://static.example.test; object-src 'none'; frame-ancestors 'self'","x-content-type-options":"nosniff","referrer-policy":"same-origin"},cookies:[],forms:[],thirdPartyOrigins:[],availability:{headers:true,page:true,cookies:true}};
const find=(data,name)=>scoring.analyze(data).findings.find(f=>f.name===name);
assert.equal(find(base,"Content-Security-Policy").status,"pass","Specific HTTPS source must not be broad");
const policy=p=>({...base,headers:{...base.headers,"content-security-policy":p}});
assert.equal(find(policy("default-src 'self'; script-src 'nonce-abc123' 'unsafe-inline'; frame-ancestors 'none'"),"Content-Security-Policy").status,"pass");
assert.equal(find(policy("default-src 'none'; script-src https:; frame-ancestors *"),"Content-Security-Policy").status,"warn");
assert.equal(find(policy("default-src 'none'; frame-ancestors *"),"Protección contra marcos").status,"warn");
assert.equal(find(policy("default-src 'none'; frame-ancestors 'none'"),"Protección contra marcos").status,"pass");
const partial=scoring.analyze({...base,headers:{},availability:{headers:false,page:false,cookies:false}});
assert.equal(partial.counts.unknown,3);
assert.equal(partial.coverage.complete,false);
assert(!partial.findings.some(f=>f.name==="Content-Security-Policy"));
assert.equal(find({...base,cookies:[{session:true,secure:true,httpOnly:false,sameSite:"lax"}]},"Cookies HttpOnly").penalty,0);
const report={...base,...scoring.analyze(base),url:"https://example.test/private?token=secret#private",localScore:95,analyzedAt:"2026-09-15T12:00:00Z",apiKey:"secret",cookies:[{value:"secret"}]};
const snap=history.snapshot(report);
assert(!JSON.stringify(snap).includes("secret"));
assert(!JSON.stringify(snap).includes("private"));
assert.equal(snap.origin,"https://example.test");
assert.equal(history.compare(snap,snap).changes.length,0);
assert(history.compare({...snap,score:90,thirds:["https://cdn.test"]},snap).changes.some(x=>x.includes("cdn.test")));
assert.equal(history.compare({...snap,complete:false},snap).changes.length,0);
const popup=fs.readFileSync(require.resolve("../src/popup.js"),"utf8");
const prefix=popup.slice(0,popup.indexOf('$("saveHistory").addEventListener'));
const ctx={WebSecHistory:history,document:{getElementById:()=>({})},console}; vm.createContext(ctx); vm.runInContext(prefix,ctx);
assert.equal(vm.runInContext('combinedScore(50,{configured:true,abuseConfidenceScore:0})',ctx),50);
assert.equal(vm.runInContext('combinedScore(50,{configured:true,abuseConfidenceScore:100})',ctx),30);
ctx.report={...report,hostname:"<script>alert(1)</script>",findings:[{name:"<img src=x onerror=alert(1)>",status:"unknown",summary:"test",recommendation:"test",penalty:0}],counts:{unknown:1},threatIntel:{}};
const html=vm.runInContext("buildHtmlReport(report)",ctx);
assert(!html.includes("<script>alert"));
assert(html.includes("&lt;script&gt;"));
assert(html.includes("No comprobado"));
const events={};
const chrome={webRequest:Object.fromEntries(["onBeforeRequest","onBeforeRedirect","onHeadersReceived"].map(n=>[n,{addListener:fn=>events[n]=fn}])),tabs:{onRemoved:{addListener:()=>{}}},runtime:{onMessage:{addListener:()=>{}}}};
const bg={chrome,console};vm.createContext(bg);vm.runInContext(fs.readFileSync(require.resolve("../src/background.js"),"utf8"),bg);
events.onBeforeRequest({tabId:1,type:"main_frame",requestId:"a",url:"http://example.test"});
events.onBeforeRedirect({tabId:1,type:"main_frame",requestId:"a",redirectUrl:"https://example.test"});
events.onBeforeRequest({tabId:1,type:"main_frame",requestId:"a",url:"https://example.test"});
assert.equal(vm.runInContext("tabState.get(1).redirects",bg),1);
events.onBeforeRequest({tabId:1,type:"main_frame",requestId:"b",url:"https://other.test"});
assert.equal(vm.runInContext("tabState.get(1).redirects",bg),0);
console.log("Regression checks passed: CSP, coverage, cookies, history privacy/comparison, scoring, HTML escaping and redirects.");
